import { Box } from "@mui/material";
import type { NextPage } from "next";
import App from "next/app";
import NavBar from "../components/navbar";
import SearchBar from "../components/searchbar";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { ThemeProvider } from "@mui/material/styles";
import { CssBaseline } from "@mui/material/";
import theme from "../styles/theme/theme";

export default function Home() {
  return (
    <ThemeProvider theme={theme}>
      <div className={styles.container}>
        <SearchBar />
        <Head>
          <title>M U T T</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}></main>
      </div>
    </ThemeProvider>
  );
}
